# Don't edit this file!
# It is automatically updated after every release of https://github.com/47degrees/.github
# If you want to suggest a change, please open a PR or issue in that repository

name: Formatters & Tests

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Set up jekyll
        run: |
          gem install jekyll -v 4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Run checks
        run: sbt ci-test
